<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

## *Data Science Unit 4 Sprint 2*

# Sprint Challenge - Neural Network Foundations

Table of Problems

1. [Defining Neural Networks](#Q1)
2. [Chocolate Gummy Bears](#Q2)
    - Perceptron
    - Multilayer Perceptron
4. [Keras MMP](#Q3)

<a id="Q1"></a>
## 1. Define the following terms:

- **Neuron:** In a biology and in ANNs a neuron is a elemental unit of information transfer -- it basically acts like a function, taking in information from one or more inputs and spits out an output. 
- **Input Layer:** The input layer is where information comes into an ANN. I think the number of neurons in this layer is equal to the number of features / variables in the data that is to be modeled. 
- **Hidden Layer:** A hidden layer is one of the intermediate staging areas of processing data in a NN. It takes in the output of the layer before it and applies it's own wieghts (sometimes biases) and dropout thresholds. In essence, hidden layers allow for a NN to adapt to subtle diferences in a feature space, but honestly, I don't know how they do that. 
- **Output Layer:** Output layer is where our NN makes a prediction based upon it's input and all the changes applied throughout the NN.
- **Activation:** Not totally clear on this, but after a layer has it's weights dot producted with the values of the previous layer, and "activation" function applied (eg sigmoid) which translates the values into something that can be passed to the next layer / the output. 
- **Backpropagation:** At each epoch, cycling all the layer of the NN, backprop readjusts the weights based upon a comparison of the output and the true answer. In other words, backpropigation is a method for decreasing error on each epoch by adjusting forward prop parameters (esp weight). 


## 2. Chocolate Gummy Bears <a id="Q2"></a>

Right now, you're probably thinking, "yuck, who the hell would eat that?". Great question. Your candy company wants to know too. And you thought I was kidding about the [Chocolate Gummy Bears](https://nuts.com/chocolatessweets/gummies/gummy-bears/milk-gummy-bears.html?utm_source=google&utm_medium=cpc&adpos=1o1&gclid=Cj0KCQjwrfvsBRD7ARIsAKuDvMOZrysDku3jGuWaDqf9TrV3x5JLXt1eqnVhN0KM6fMcbA1nod3h8AwaAvWwEALw_wcB). 

Let's assume that a candy company has gone out and collected information on the types of Halloween candy kids ate. Our candy company wants to predict the eating behavior of witches, warlocks, and ghosts -- aka costumed kids. They shared a sample dataset with us. Each row represents a piece of candy that a costumed child was presented with during "trick" or "treat". We know if the candy was `chocolate` (or not chocolate) or `gummy` (or not gummy). Your goal is to predict if the costumed kid `ate` the piece of candy. 

If both chocolate and gummy equal one, you've got a chocolate gummy bear on your hands!?!?!
![Chocolate Gummy Bear](https://ed910ae2d60f0d25bcb8-80550f96b5feb12604f4f720bfefb46d.ssl.cf1.rackcdn.com/3fb630c04435b7b5-2leZuM7_-zoom.jpg)

In [75]:
import pandas as pd
candy = pd.read_csv('chocolate_gummy_bears.csv')

In [94]:
candy['ate'].value_counts()

1    5000
0    5000
Name: ate, dtype: int64

In [76]:
candy.head()

chocolate  gummy  ate
0          0      1    1
1          1      0    1
2          0      1    1
3          0      0    0
4          1      1    0

### Perceptron

To make predictions on the `candy` dataframe. Build and train a Perceptron using numpy. Your target column is `ate` and your features: `chocolate` and `gummy`. Do not do any feature engineering. :P

Once you've trained your model, report your accuracy. Explain why you could not achieve a higher accuracy with a *simple perceptron*. It's possible to achieve ~95% accuracy on this dataset.

In [77]:
# Start your candy perceptron here

X = candy[['chocolate', 'gummy']].values
y = candy['ate'].values

In [6]:
import numpy as np

In [4]:
y

array([1, 1, 1, ..., 1, 1, 1])

In [78]:
y = np.array([y]).T
y.shape

(10000, 1)

In [40]:
X.shape

(10000, 2)

In [79]:
class Perceptron(object):
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # weights
        self.weight = np.zeros(1 + X.shape[1])

        # Number of misclassifications
        self.errors = []  # Number of misclassifications

        for i in range(self.niter):
            err = 0
            for xi, target in zip(X, y):
                delta_w = self.rate * (target - self.predict(xi))
                self.weight[1:] += delta_w * xi
                self.weight[0] += delta_w
                err += int(delta_w != 0.0)
                self.errors.append(err)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        """Return class label after unit step"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

In [85]:
pn = Perceptron(0.01, 100)

In [86]:
pn.fit(X, y)

In [87]:
pn.predict(X)

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
pn.errors

import matplotlib.pyplot as plt

plt.plot(range(1, len(pn.errors) + 1), pn.errors, marker='o')
plt.xlabel('Epochs')
plt.ylabel('Number of misclassifications')
plt.show()

In [ ]:
# Come back to this.... Haven't looked at accuracy...

In [73]:
from sklearn.metrics import accuracy_score

In [88]:
y_pred = pn.predict(X)

In [90]:
print(accuracy_score(y, y_pred))

0.5


In [ ]:
# ugh. Not good. 

In [24]:
# Refelction: I didn't expect great results, but these just seem wrong. 
# Being able to adjust due to error would have been the main issue I would 
# expect with a simple, one layer-feedforward, dense NN. I also don't have 
# any control of the finer tune nobs to tweek the model and make it work. 
# I don't know what's going on here, but the issue I fought with most in the 
# assignment was getting the model to do anything but converge towards one or 
# another value for the whole prediction. I think it has to do with the weights changing 
# too rapidly between epochs. 

### Multilayer Perceptron <a id="Q3"></a>

Using the sample candy dataset, implement a Neural Network Multilayer Perceptron class that uses backpropagation to update the network's weights. Your Multilayer Perceptron should be implemented in Numpy. 
Your network must have one hidden layer.

Once you've trained your model, report your accuracy. Explain why your MLP's performance is considerably better than your simple perceptron's on the candy dataset. 

In [91]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher

class NeuralNetwork3:
    def __init__(self, inputs=2, h_nodes=3, output=1):
        # Set up Architecture of Neural Network
        self.inputs = inputs
        self.hiddenNodes = h_nodes
        self.outputNodes = output

        # Initial Weights
        # 2x3 Matrix Array for the First Layer
        np.random.seed(421)
        self.weights1 = np.random.rand(self.inputs, self.hiddenNodes) * .01
       
        # 3x1 Matrix Array for Hidden to Output
        self.weights2 = np.random.rand(self.hiddenNodes, self.outputNodes) * .01
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        aka "predict"
        """
        
        # Weighted sum of inputs => hidden layer
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activations of weighted sum
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weight sum between hidden and output
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final activation of output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
        
    def backward(self, X,y,o):
        """
        Backward propagate through the network
        """
        
        # Error in Output
        self.o_error = y - o
        
        # Apply Derivative of Sigmoid to error
        # How far off are we in relation to the Sigmoid f(x) of the output
        # ^- aka hidden => output
        self.o_delta = self.o_error * self.sigmoidPrime(o)
        
        # z2 error
        self.z2_error = self.o_delta.dot(self.weights2.T)
        # How much of that "far off" can explained by the input => hidden
        self.z2_delta = self.z2_error * self.sigmoidPrime(self.activated_hidden)
        
        # Adjustment to first set of weights (input => hidden)
        self.weights1 += X.T.dot(self.z2_delta)
        # Adjustment to second set of weights (hidden => output)
        self.weights2 += self.activated_hidden.T.dot(self.o_delta)
        

    def train(self, X, y, n_itr):
        for i in range(n_itr):
            o = self.feed_forward(X)
            self.backward(X,y,o)
            
    def predict(self, X):
        print('Predicted Output: \n' + str(self.feed_forward(X)))
        return

    def verbose(self, X, y, n_itr):
        for i in range(n_itr):
            if (i+1 in [1,2,3,4,5]) or ((i+1) % 1000 ==0):
                print('+' + '---' * 3 + f'EPOCH {i+1}' + '---'*3 + '+')
                print('Input: \n', X)
                print('Actual Output: \n', y)
                print('Predicted Output: \n', str(self.feed_forward(X)))
                print("Loss: \n", str(np.mean(np.square(y - self.feed_forward(X)))))
            o = self.feed_forward(X)
            self.backward(X,y,o)

In [92]:
NN = NeuralNetwork3()

In [93]:
NN.train(X, y, 1000)
NN.predict(X)

Predicted Output: 
[[0.5]
 [0.5]
 [0.5]
 ...
 [0.5]
 [0.5]
 [0.5]]


In [47]:
NN.verbose(X, y, 10)

+---------EPOCH 1---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.50185695]
 [0.50185896]
 [0.50185695]
 ...
 [0.50185695]
 [0.50185695]
 [0.50185896]]
Loss: 
 0.25000344595993035
+---------EPOCH 2---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.02971935]
 [0.02967946]
 [0.02971935]
 ...
 [0.02971935]
 [0.02971935]
 [0.02967946]]
Loss: 
 0.47118263120403464
+---------EPOCH 3---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5]
 [0.5]
 [0.5]
 ...
 [0.5]
 [0.5]
 [0.5]]
Loss: 
 0.4247499999999999
+---------EPOCH 4---------+
Input: 
 [[0 1]
 [1 0]
 [0 1]
 ...
 [0 1]
 [0 1]
 [1 0]]
Actual Output: 
 [[1]
 [1]
 [1]
 ...
 [1]
 [1]
 [1]]
Predicted Output: 
 [[0.5]
 [0.5]
 [0.5]
 ...
 [0.5]
 [0.5]
 [0.5]]
Loss: 
 0

In [96]:
y_pred = NN.feed_forward(X)

In [106]:
unique, counts = np.unique(y, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 5000]
 [   1 5000]]


In [107]:
unique, counts = np.unique(y_pred, return_counts=True)
print(np.asarray((unique, counts)).T)

[[5.000e-01 2.502e+03]
 [5.000e-01 4.980e+03]
 [1.000e+00 2.518e+03]]


In [108]:
y_pred

array([[0.5],
       [0.5],
       [0.5],
       ...,
       [0.5],
       [0.5],
       [0.5]])

In [116]:
y_pred = np.round(y_pred, 0)
y_pred

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [117]:
y_pred = y_pred.astype(int)

In [118]:
unique, counts = np.unique(y_pred, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   0 2502]
 [   1 7498]]


In [119]:
print(accuracy_score(y, y_pred))

0.7222


In [ ]:
# Well, it's a number. A slightly more reasonable number, but I need to tweek 
# and adjust the model manually to get better results. Already, this makes way 
# more sense than the last one. Maybe I'm not rounding at the end of the first 
# model. I realized when I started the SC that I hadn't built an accuracy function 
# in any of my perceptron classes. They also didn't exist in any of the lecture 
# perceptron classes. I guess I should have known I would need it and should have 
# built it in advance. I'm sure I could have made an iterative function to avoid an 
# import from sklearn, but it works. 

P.S. Don't try candy gummy bears. They're disgusting. 

## 3. Keras MMP <a id="Q3"></a>

Implement a Multilayer Perceptron architecture of your choosing using the Keras library. Train your model and report its baseline accuracy. Then hyperparameter tune at least two parameters and report your model's accuracy.
Use the Heart Disease Dataset (binary classification)
Use an appropriate loss function for a binary classification task
Use an appropriate activation function on the final layer of your network.
Train your model using verbose output for ease of grading.
Use GridSearchCV or RandomSearchCV to hyperparameter tune your model. (for at least two hyperparameters)
When hyperparameter tuning, show you work by adding code cells for each new experiment.
Report the accuracy for each combination of hyperparameters as you test them so that we can easily see which resulted in the highest accuracy.
You must hyperparameter tune at least 3 parameters in order to get a 3 on this section.

In [120]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/heart.csv')
df = df.sample(frac=1)
print(df.shape)
df.head()

(303, 14)


age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
31    65    1   0       120   177    0        1      140      0      0.4   
261   52    1   0       112   230    0        1      160      0      0.0   
267   49    1   2       118   149    0        0      126      0      0.8   
63    41    1   1       135   203    0        1      132      0      0.0   
165   67    1   0       160   286    0        0      108      1      1.5   

     slope  ca  thal  target  
31       2   0     3       1  
261      2   1     2       0  
267      2   3     2       0  
63       1   0     1       1  
165      1   3     2       0

In [ ]:
# All numeric X, binary target y

In [121]:
# X, y split

y = df['target']
X = df.drop(['target'], axis='columns')

In [122]:
y.value_counts()

1    165
0    138
Name: target, dtype: int64

In [123]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X, y)

In [124]:
x_train = np.array(x_train)
x_test = np.array(x_test)

y_train = np.array([y_train]).T
y_test = np.array([y_test]).T

In [125]:
from sklearn.preprocessing import Normalizer

# use Normalizer to transform array to 0,1
x_train = Normalizer().fit(x_train).transform(x_train)
x_test = Normalizer().fit(x_test).transform(x_test) # Hold off on running...

In [63]:
x_train

array([[0.13323524, 0.00256222, 0.00256222, ..., 0.00512443, 0.        ,
        0.00512443],
       [0.13933   , 0.        , 0.00309622, ..., 0.00309622, 0.        ,
        0.00619244],
       [0.15059554, 0.        , 0.00278881, ..., 0.00557761, 0.00278881,
        0.00557761],
       ...,
       [0.21573562, 0.0031266 , 0.00937981, ..., 0.0031266 , 0.0031266 ,
        0.00625321],
       [0.20562012, 0.00267039, 0.        , ..., 0.00534078, 0.00801117,
        0.00534078],
       [0.15474241, 0.        , 0.        , ..., 0.0061897 , 0.        ,
        0.0061897 ]])

In [58]:
x_train.shape

(227, 13)

In [126]:
y_train.shape

(227, 1)

In [127]:
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Important Hyperparameters
inputs = x_train.shape[1]
epochs = 50
batch_size = 10


# Create Model
model = Sequential()
model.add(Dense(17, activation='relu', input_dim=inputs))
model.add(Dense(17, activation='relu'))
model.add(Dense(1))
# Compile Model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Fit Model

model.fit(x_train, y_train,
          validation_data=(x_test, y_test),
          epochs=epochs,
          batch_size=epochs,
#           verbose=True
         )

# Pretty horrible...

Train on 227 samples, validate on 76 samples
Epoch 1/50
227/227 [==============================] - 1s 3ms/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 2/50
227/227 [==============================] - 0s 147us/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 3/50
227/227 [==============================] - 0s 142us/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 4/50
227/227 [==============================] - 0s 136us/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 5/50
227/227 [==============================] - 0s 150us/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 6/50
227/227 [==============================] - 0s 139us/sample - loss: 8.4260 - accuracy: 0.4537 - val_loss: 8.3214 - val_accuracy: 0.4605
Epoch 7/50
227/227 [==============================] - 0s 140us/sample - loss: 8.4

In [129]:
import numpy
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier # There's a KerasRegressor too...

# seed just for fun...
seed = 777
numpy.random.seed(seed)
inputs = x_train.shape[1]

X = x_train
Y = y_train

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(21, input_dim=inputs, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=20, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [20, 40],
              'epochs': [100, 200]
              
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1) # make sure n_jobs is 1 for keras classifier...
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.7709251216854818 using {'batch_size': 20, 'epochs': 200}
Means: 0.7092510984332551, Stdev: 0.03399448911062261 with: {'batch_size': 20, 'epochs': 100}
Means: 0.7709251216854818, Stdev: 0.03617461631741407 with: {'batch_size': 20, 'epochs': 200}
Means: 0.6784140995420548, Stdev: 0.07216902143556027 with: {'batch_size': 40, 'epochs': 100}
Means: 0.7356828133440227, Stdev: 0.023051216964497558 with: {'batch_size': 40, 'epochs': 200}


In [ ]:
# Ah Ha!!!! more layers!!!!

In [130]:
import numpy
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier # There's a KerasRegressor too...

# fix random seed for reproducibility
seed = 777
numpy.random.seed(seed)
inputs = x_train.shape[1]

X = x_train
Y = y_train

optimizer = 'Adam'

# Function to create model, required for KerasClassifier
def create_model(learn_rate=0.01, momentum=0.1):
    # create model
    model = Sequential()
    model.add(Dense(21, input_dim=inputs, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=200, batch_size=20, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
learn_rate = [0.01, 0.1]
momentum = [0.1, 0.3, 0.5, 0.8]
param_grid = dict(learn_rate=learn_rate, momentum=momentum)

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1, cv=3) # make sure n_jobs is 1 in paperspace ... ?
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.7488986818275788 using {'learn_rate': 0.01, 'momentum': 0.3}
Means: 0.7224669448604668, Stdev: 0.012335495235717326 with: {'learn_rate': 0.01, 'momentum': 0.1}
Means: 0.7488986818275788, Stdev: 0.030149969590533194 with: {'learn_rate': 0.01, 'momentum': 0.3}
Means: 0.7268722417071002, Stdev: 0.02856341512569334 with: {'learn_rate': 0.01, 'momentum': 0.5}
Means: 0.7312775312016189, Stdev: 0.04187801271869096 with: {'learn_rate': 0.01, 'momentum': 0.8}
Means: 0.7488986818275788, Stdev: 0.030149969590533194 with: {'learn_rate': 0.1, 'momentum': 0.1}
Means: 0.7312775312016189, Stdev: 0.028746093972061283 with: {'learn_rate': 0.1, 'momentum': 0.3}
Means: 0.7400881049391457, Stdev: 0.05588918627857447 with: {'learn_rate': 0.1, 'momentum': 0.5}
Means: 0.7224669669168111, Stdev: 0.039196313165996644 with: {'learn_rate': 0.1, 'momentum': 0.8}


In [ ]:
# not impressed. 

In [132]:
import numpy
from sklearn.model_selection import GridSearchCV
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasClassifier # There's a KerasRegressor too...

# seed just for fun...
seed = 777
numpy.random.seed(seed)
inputs = x_train.shape[1]

X = x_train
Y = y_train

# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(21, input_dim=inputs, activation='linear'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=100, batch_size=20, verbose=0)

# define the grid search parameters
# batch_size = [10, 20, 40, 60, 80, 100]
# param_grid = dict(batch_size=batch_size, epochs=epochs)

# define the grid search parameters
param_grid = {'batch_size': [10],
              'epochs': [200, 300]
              
             }

# Create Grid Search
grid = GridSearchCV(estimator=model, param_grid=param_grid, n_jobs=1) # make sure n_jobs is 1 for keras classifier...
grid_result = grid.fit(X, Y)

# Report Results
print(f"Best: {grid_result.best_score_} using {grid_result.best_params_}")
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print(f"Means: {mean}, Stdev: {stdev} with: {param}")

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


Best: 0.850220253551584 using {'batch_size': 10, 'epochs': 300}
Means: 0.8149779893228136, Stdev: 0.05835236176604968 with: {'batch_size': 10, 'epochs': 200}
Means: 0.850220253551584, Stdev: 0.023120880990635022 with: {'batch_size': 10, 'epochs': 300}


In [ ]:
# Above: changed initial activation to linear.

In [ ]:
# Important Hyperparameters
import wandb
from wandb.keras import WandbCallback
wandb.init(project="sprint_challenge", entity="lambda-ds6") #initializes and experiment


X = x_train
y = y_train

inputs = X.shape[1]

# wandb.config.epochs = 300    # notice the wandb --> tracks the changes to this variable
# wandb.config.batch_size = 10


# Function to create model, required for KerasClassifier
def create_model():
    # create model
    model = Sequential()
    model.add(Dense(21, input_dim=inputs, activation='linear'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(14, activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# create model
model = KerasClassifier(build_fn=create_model, epochs=300, batch_size=10, verbose=0)

# Fit Model

model.fit(X, y, 
          validation_split=0.2, 
          epochs=wandb.config.epochs,       # make sure your paremeters are right too...
          batch_size=wandb.config.epochs, 
          callbacks=[WandbCallback()]       # where we send data to after evaluation
         )